version: '3.8'

services:
  php:
    image: php:8.1-fpm
    container_name: moodle-php
    working_dir: /workspace
    volumes:
      - ../:/workspace:cached
      - ./php/php.ini:/usr/local/etc/php/conf.d/moodle.ini
    depends_on:
      - mysql
    networks:
      - moodle-network

  nginx:
    image: nginx:alpine
    container_name: moodle-nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ../:/workspace:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - moodle-network

  mysql:
    image: mysql:8.0
    container_name: moodle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: CodespacePass123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - moodle-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: moodle-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - moodle-network

networks:
  moodle-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
